http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/api/flights'
serviceEndpoints:
  httpbin:
    url: 'http://localhost:50041'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: my-gateway
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
          - action:
              apiKeyHeader: COMPANY-CUSTOM-API-KEY-HEADER
              apiKeyHeaderScheme: key-pair
              disableHeadersScheme: true
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
